### PR TITLE
Fix SaveImage in incognito

### LINKED ISSUE #691: Images are downloaded in regular window while it should be in incognito window
### Describe your matter in detail

Saving images with Gesturefy in incognito window will redirect them to regular window's download list, which could potentially be considered a privacy concern.

### Your System
- Operating system: Windows 10
- Firefox version: 120.0 (64-bit)
- Gesturefy version: 3.2.10

### PR DESCRIPTION
**Pull request by whfuyn**
Fix #691 .

### CODE REVIEW

File: src/core/commands.mjs [hunk 1]
```diff
@@ -1794,6 +1794,8 @@ export async function SaveImage (sender, data) {
       queryOptions.headers = [ { name: "Referer", value: documentValues.referrer } ];
     }
 
+    // download in incognito window if currently in incognito mode
+    queryOptions.incognito = (await browser.windows.getCurrent()).incognito;
```
Comment (Robbendebiene) [inline src/core/commands.mjs:1798]: I think we can simply use `sender.tab.incognito`.
Also can you please add it directly here: https://github.com/Robbendebiene/Gesturefy/blob/43819d5c67c99417407f34ce1baf8ddaa0f1232b/src/core/commands.mjs#L1757-L1759

**Review by Robbendebiene — CHANGES_REQUESTED** [review]
Thanks a lot for your PR.

**Review by Robbendebiene — APPROVED** [review]
Thanks you 🙂
